[package]
name = "self_destructor"
version = "0.1.0"
authors = ["q9good <psnyima@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
lazy_static = "1.4.0"
